development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  username: root
  password: root
  pool: 5
  database: pure_loan_development


production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: pure_loan_development