development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 12345678
  pool: 5
  database: pure_loan_development_new_1


production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  username: root
  password: root
  pool: 5
  database: pure_loan_development